### ISSUE TITLE
Wasmer  build using emcc --preload fails

### ISSUE THREAD

**Issue by jonghough** [jsoftware/j-playground#26]
The wasmer build seems to fail.

Build command
```
make -f makefile.wasmer clean j
```

Error is

```
Error: Embedding "../jlibrary/copy_library_from_current.bat" which is below the current directory "/host_tmp/j-playground/jsrc". This is invalid since the current directory becomes the root that the generated code will see
emcc: error: '/emsdk/upstream/emscripten/tools/file_packager ../bin/wasmer/emj.data --from-emcc --export-name=Module --preload ../jlibrary' failed (returned 1)
make: *** [makefile.wasmer:25: j] Error 1
```

If I copy the `jlibrary` into the `jsrc` dir
```
cp -R ../jlibrary ./
```
and modify `makefile.wasmer` to use this directory (i.e. `--preload-file jlibrary`). The whole build process completes.

I am building this in the docker container, so it is strange that only I am seeing this error.

emcc version
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.3 (c06156773675b2cb437e41459c12d44bd9a8f235)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by joebo** [comment]
It looks like this behavior changed between emcc 3.1.0 and 3.1.3. I confirmed I also have the issue on the latest emscripten docker

I deprioritized the wasmer build since it had some nuances and wasn't directly related to the web objective. However, I've been meaning to get back to it so we can run tests in a more automated way.

Changing the preload to ../jlibrary@jlibrary should resolve the issue but there are some other issues with like clock_gettime with the latest rev of the emscripten toolchain and wasmer. I'll dig in more later. The wasm_stubs.h needs to be updated I think... I also want to remove the stubs so we can get file access working again. The preloads aren't working on wasmer which I think is because I stubbed out the file io stuff in an earlier attempt to get the wasmer build working

**Comment by jonghough** [comment]
` ../jlibrary@jlibrary` fixes the emcc buildissue, as you said.
Now, in my env, when I try to run
```
wasmer ../bin/wasmer/emj.wasm
```
I get the error.

```
error: failed to run `../bin/wasmer/emj.wasm`
│   1: RuntimeError: unreachable
           at <unnamed> (emj.wasm[544]:0x135ab0)
           at <unnamed> (emj.wasm[2655]:0x7b68a2)
╰─▶ 2: unreachable

```
I need to look into how to debug that.

**Comment by joebo** [comment]
The unreachable error is 'normal' on wasmer. It's failing on cleanup on exit or something like that... If you want to see it do something you need to hack something into emj.c

Something like:

in main()
```
#if HTML
 //load stdlib
 em_jdo("(0!:0) <'jlibrary/system/main/stdlib.ijs'");
 em_jdo("(0!:0) <'emj.ijs'");
#elif WASMER
 /*
 em_jdo("smoutput =: 0 0 $ 1!:2&2");
 em_jdo("smoutput 'hello world'");
 em_jdo("z=: (1!:0) '*'");
 em_jdo("smoutput z");
 em_jdo("smoutput 'hello world'");
 */
#endif
```
