### ISSUE TITLE
Plot output overflows outside viewport

### ISSUE THREAD

**Issue by razetime** [jsoftware/j-playground#56]
On the example link https://jsoftware.github.io/j-playground/bin/html/emj.html#code='key%20sin(exp)%2Ccos(exp)'%20plot%20(%3B(sin%2C%3Acos)%40%3A%5E)%20-%3A%20%3E%3A%20i%3A3j100 , Clicking the run button repeatedly creates plots that move outside the visible screen area.

**Comment by JoeBognerINSIGHT** [comment]
Thanks for writing up. This issue only affects the prototype version of the playground. I would recommend that we deprioritize it or don't fix it since the prototype playground is likely going to be decommissioned

**Comment by razetime** [comment]
Alright. I will close this issue once the prototype is decommmissioned.

**Comment by joebo** [comment]
Sorry for the duplicate/deleted comments. I was signed in on the wrong GitHub account. Here is the comment I initially wrote above yours (just for history)

Thanks for writing up. This issue only affects the prototype version of the playground. I would recommend that we deprioritize it or don't fix it since the prototype playground is likely going to be decommissioned

**Comment by joebo** [comment]
Closing this since the emj.html has been decomissioned
