### ISSUE TITLE
Updates to the playground

### ISSUE THREAD

**Issue by cdburke** [jsoftware/j-playground#67]
Updates to the playground (clear browser cache first):

1. Box drawing lines are now the default.

2. Both plot and viewmat need to be explicitly loaded.

3. The viewmat example runs to completion without error.

4. Context sensitive help works, see Help|Context Sensitive

**Comment by joebo** [comment]
Looks great and thanks for working on it. Curious about the change to require plot and viewmat to be explicitly loaded. I was on the fence about that initially and opted to make it loaded by default. 

Advantages:
1. One less thing for someone to have to type since plot and viewmat were bundled with the playground
Disadvantages:
1. Less compatibility to copy/paste into jqt 

Did you opt to make it explicitly loaded to make it more compatible with standard J or was there some other benefit?

**Comment by cdburke** [comment]
I saw that in the previous version, viewmat had to be loaded up front because loading it later failed. So I assumed this explained the load up front. That problem is now fixed, so viewmat can be loaded at any time.

In a normal J session, you need to explicitly load plot and viewmat, just like any other addon. So I felt that would be best in the playground. Also, there are plot and viewmat example scripts, both of which will start with the explicit load.

So I do prefer the explicit load, but don't feel too strongly about it.

**Comment by joebo** [comment]
Ok, that all makes sense to me too. I am also not strongly leaning in any
direction so I support keeping it explicit. Thanks again
