### ISSUE TITLE
New sessions starting in jws, also CODE assignment leaking into base

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#69]
18!:5 ''
┌───┐
│jws│
└───┘
   cocurrent'base'
   18!:5 ''
┌────┐
│base│
└────┘
   names''
CODE

**Comment by cdburke** [comment]
Fixed.

**Comment by plj541** [comment]
Yes, everything I reported, but one new name left in base. Please advise
about this situation, reopen or start a new issue.

   18!:5 ''
┌────┐
│base│
└────┘
   names''
install
3 : (9 105 110 115 116 97 108 108 95 103 105 116 114 101 112 111 95 106 112
97 99 109 97 110 95 32 121{a.)
 (9 105 110 115 116 97 108 108 95 103 105 116 114 101 112 111 95 106 112 97
99 109 97 110 95 32 121{a.)
install_gitrepo_jpacman_ y

**Comment by joebo** [comment]
'install' showing up base is my new contribution from today. I'm not a pro
at using locales -- more beginner level. What locale should that show up in
-- my only other thought was "z" ... ? I can move it to z

" Since we can find in z things which are not in base, locale z is the
natural home for functions of general utility. On starting a J session,
locale z is automatically populated with a collection of useful predefined
"library" functions." https://www.jsoftware.com/help/learning/24.htm but
want to confirm that's the right home before moving it.

**Comment by rdm** [comment]
Yeah, z is the right place. This would have to be after the other assignment of install_z_ so that it overrides the default definition.

If that's a problem, leaving it in base until we can get things sorted out might be an acceptable temporary workaround.

Anyways, ... z is where all of the system definitions go that need to be available in base (and elsewhere).

**Comment by cdburke** [comment]
I will fix this.

**Comment by cdburke** [comment]
install is now in z

**Comment by plj541** [comment]
This little gem helped find issue #77 on j-plaground.
u. will create an adverb, v. won't create a conjunction

adv=.{{
 u. y
}}

cnj=.{{
 (u. y)v. y
}}
