### ISSUE TITLE
geometric average example

### ISSUE THREAD

**Issue by zino113** [jsoftware/j-playground#8]
The code example listed as "geometric mean of matrix columns"
   %: +/ *: i. 3 4
8.94427 10.3441 11.8322 13.3791
isn't the geometric mean but rather the length of the vector defined by the column elements.
   i. 3 4
0 1  2  3
4 5  6  7
8 9 10 11
First column contains a zero, so geometric mean of that column should be 0.
   3 %: */ 0 4 5
0
   3 %: */ i. 3 4
0 3.55689 4.93242 6.13579

-M

**Comment by joebo** [comment]
Thanks for logging this issue. I thought about fixing the example using the reference from https://code.jsoftware.com/wiki/JPhrases/SumsMeans but instead, I opted to remove it and the example of loading stdlib. If someone wants to add back geometric mean or other examples, feel free. I wasn't convinced it was a common enough example to justify being in )play and instead of fixing it, it was easier to remove.

Stdlib was removed from )play since it's loaded by default now
